### ISSUE TITLE
Is possible set avatar for jabber account of hubot?

### ISSUE THREAD

**Issue by a-x-** [smoak/hubot-jabbr#11]
Hi, guys!
And excuse my beginner's English
Subj?

----
I also ask here: https://github.com/github/hubot/issues/946

**Comment by smoak** [comment]
The jabber server supports it using `/gravatar <gravatar email>` but I will have to add in that option

**Comment by a-x-** [comment]
i not sure my possibilities :smile:

**Comment by smoak** [comment]
I added the ability to set the gravatar. See the [https://github.com/smoak/hubot-jabbr/blob/master/README.md](https://github.com/smoak/hubot-jabbr/blob/master/README.md) for instructions.
